= Renovate

== Config

=== depName

==== Go
Usually module name, which is used as `depName` is present at the top of `go.mod` file of the package. +
To monitor specific binary (or something) of the package instead of the package itself, append the `tag` for that release without version part. +
.e.g. atlas CLI (deprecated)
----
# renovate: datasource=go depName=ariga.io/atlas/cmd/atlas versioning=semver
----
Here, `ariga.io/atlas` is the module name, and `cmd/atlas` is the tag without version.

== Tips
Run Renovate locally::
+
[source,shell]
----
docker run --interactive --tty --rm --volume ./:/usr/src/app renovate/renovate:latest --platform=local --dry-run=full
----
Packages/Dependencies that are not up to date are logged as `WARN`.

Test renovate config::
Wnen testing new `renovate.json`, it is likely to create new branch, modify `renovate.json`, then run renovate CI job. +
By default, renovate uses the config on the default branch and scan dependencies on the default branch. +
To instruct renovate to see another branch, you need to set environment variables. +
Also it is useful to dry run the renovate so that pull/merge requests are not created.
+
[source,shell]
----
RENOVATE_BASE_BRANCHES=<branch>
RENOVATE_USE_BASE_BRANCH_CONFIG=merge
RENOVATE_DRY_RUN=full
----
