= Renovate

== Config

=== depName

==== Go
Usually module name, which is used as `depName` is present at the top of `go.mod` file of the package. +
To monitor specific binary (or something) of the package instead of the package itself, append the `tag` for that release without version part. +
.e.g. atlas CLI (deprecated)
----
# renovate: datasource=go depName=ariga.io/atlas/cmd/atlas versioning=semver
----
Here, `ariga.io/atlas` is the module name, and `cmd/atlas` is the tag without version.

== Tips
Run Renovate locally::
+
[source,shell]
----
docker run --interactive --tty --rm --volume ./:/usr/src/app --env LOG_LEVEL=debug --env GITHUB_COM_TOKEN=<GITHUB_TOKEN> renovate/renovate:latest --platform=local --dry-run=lookup
----
* Updatable packages/dependencies will have non-empty `updates` json field.
* `GITHUB_COM_TOKEN` is required to check updates for `github-releases` datasource.
* Renovate will run as non-root user, so add `--user root` if there are files that renovate cannot read in bind-mounted files
* If you need to `netrc`, bind-mount it as in `--volume $HOME/.netrc:/home/ubuntu/.netrc:ro`

Test renovate config::
While the above method reflects the local change in `renovate.json`, you might want to make sure that it works in CI environment.
In such cases, it is likely to create new branch, modify `renovate.json`, then run renovate CI job. +
By default, renovate uses the config on the default branch and scan dependencies on the default branch. +
To instruct renovate to see another branch, set the below environment variables. +
Also it is useful to dry run the renovate so that pull/merge requests are not created.
+
[source,shell]
----
RENOVATE_BASE_BRANCHES=<branch>
RENOVATE_USE_BASE_BRANCH_CONFIG=merge
RENOVATE_DRY_RUN=full
----
