= Windows Tips

==== How to find out which process is using a file/directory

Install `handle.exe`::

Usage (for 64bit PC):
[source,shell]
----
handle64.exe <filename>
----

Use built-in `Resource Monitor`::

. Open `Resource Monitor`
. Select `CPU` tab
. Enter file name into the textbox on `Associated Handles` and press "Enter" +
  -> Processes using the file will be displayed.

Reference: link:https://stackoverflow.com/questions/3565218/how-to-know-what-process-is-using-a-given-file[filesystems - Find out which process is locking a file or folder in Windows - Super User]

==== How to hide installed programs from Programs and Features (and Apps & Features)
See link:http://woshub.com/how-to-hide-installed-programs-from-programs-and-features/[this website]

==== Prevent apps from pinning themselves
. Open file `$env:USERPROFILE/AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml` +
  If this does not work, modify `C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml`
. Find `CustomTaskbarLayoutCollection` tag
. Remove the entries inside `TaskbarPinList`

==== Create short cut launching via powershell
Icon of shortcuts for some program (eg. Microsoft Edge, Google Chrome) which are pinned to start menu somehow remains unchanged even when you change it via `properties`. +
A workaround is start such program via powershell. +

.Example
[source,powershell]
----
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -WindowStyle Hidden -Command "Start-Process ${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe -Args www.bing.com"
----

==== Change icon of program / shortcut to any image
. Copy and paste image into `paint` program.
. Save the image as bitmap (BMP).
. Rename and change the extension of the image to `ico`.
. Select the image as icon.
