= Windows Terminal

== Install

=== Without Microsoft Store
See link:https://github.com/microsoft/terminal#other-install-methods[Other install methods].

== Configuration

=== General

==== Always open maximised
Add below to the top layer.
[source,json]
----
    "launchMode": "maximized"
----
==== Change default shell to ubuntu
By setting default profile::
. Run `uuidgen` and take a note of the output
. Replace the value of `defaultProfile` in `setting.json` (located at the top).

By changing profile order::
. In the `profiles` section of `setting.json`, sort profiles as you like. +
  The profile at the top will be used when the terminal is opened. +
  Also, the order of these profiles corresponds to the keyboard shortcut to open
  shell such as `Ctrl+Shift+1`. +

==== Profile setting
Add snippets under `profiles.defaults` to apply all shells or section for specific shell under `profiles.list`. +
Create `profiles.defaults` field if not exists.

Font::
To use font that can display glyphs, intall fonts of your choise from link:https//www.nerdfonts.com/[nerd fonts]. +
To install, donwload a font, extract it and double click one of `ttf/otf` file. +
Then add fields like below to `settings.json`.
[source,json]
----
            "font":
            {
                "face": "<Font name>"
            }
----
`<Font name>` is what is displayed on OS Fonts setting. +
`CaskaydiaCove` looks best but the down side is that it renders `.=`, `!=` and etc.

Cursor shape::
[source,json]
----
"cursorShape": "filledBox"
----

Color scheme::
[source,json]
----
"colorScheme": "Campbell"
----

=== Ubuntu
Go to ubuntu section `profiles -> list`

==== Change starting directory
. Add `"startingDirectory": "//wsl$/Ubuntu/<linux path to directory>"` to the
   section. +
   eg. `"startingDirectory": "//wsl$/Ubuntu/home/user"`

=== Keybind
Paste value of `actions` below into `setting.json`.
[source,json]
----
{
    "actions":
    [
        {
            "command": "unbound",
            "keys": "ctrl+comma"
        },
        {
            "command": "unbound",
            "keys": "win+sc(41)"
        },
        {
            "command":
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+shift+c"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": "openTabRenamer",
            "keys": "ctrl+shift+r"
        },
        {
            "command": "paste",
            "keys": "ctrl+shift+v"
        },
        {
            "command":
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ],
}
----
