= Windows Terminal

== Install

=== Without Microsoft Store
See link:https://github.com/microsoft/terminal#other-install-methods[Other install methods].

== Configuration

=== General

==== Always open maximised
Add below to the top layer.
[source,json]
----
    "launchMode": "maximized",
----
==== Change default shell to ubuntu
By setting default profile::
. Run `uuidgen` and take a note of the output
. Replace the value of `defaultProfile` in `setting.json` (located at the top).

By changing profile order::
. In the `profiles` section of `setting.json`, sort profiles as you like. +
  The profile at the top will be used when the terminal is opened. +
  Also, the order of these profiles corresponds to the keyboard shortcut to open
  shell such as `Ctrl+Shift+1`. +

==== Profile setting
Add snippets under `profiles.defaults` to apply all shells or section for specific shell under `profiles.list`. +
Create `profiles.defaults` field if not exists.

Font::
To use font that can display glyphs, intall fonts of your choise from link:https://www.nerdfonts.com/[nerd fonts]. +
(`CaskaydiaMono Nerd Font` is my current favorite) +
To install:
* Donwload a font
* Extract it and double click `ttf/otf` files (`ttf` is recommended)
** There might be several font families in the extracted directory. Install all styles of the font family you want to use (eg. Regular, Bold, Italic and etc)
*** e.g. `CaskaydiaMonoNerdFontMono-*.ttf` for `CaskaydiaMono Nerd Font`
*** Refer to README of the font for more detail
* Add fields like below to `settings.json`.
** `<Font name>` is what is displayed on OS Fonts setting. Pick one from Windows Terminal Setting GUI if you are not sure. +
** `font.feature.liga` is to turn on/off ligatures (such as `.=`, `!=`), but seems not working. It might be for `otf` only. +
+
[source,json]
----
            "font":
            {
                "face": "<Font name>",
                "features": {
                    "liga": 0
                }
            }
----
For more detail, see https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#font.

Font patching::
[NOTE]
====
For my usage, the below fonts do not need patching. +

* CaskaydiaMono Nerd Font
====
Nerd fonts might not provide all icons and if so, you need to patch nerd fonts with link:https://github.com/microsoft/vscode-codicons[codicons]. +
Follow the instruction link:https://github.com/mortepau/codicons.nvim#how-to-patch-fonts[here]. +
Install `fontforge` using `apt` or other package manager so that dependencies are automatically resolved. +
The below complements each of the instruction.
. `font-patcher` is located at the root of the repository.
. Not needed if No.3 is done.
. You can download whole `src/glyphs` directory using link:https://downgit.evecalm.com/#/home[DownGit]. +
** Simply paste the URL of directory you want to download +
** It is recommended to download the whole `src/glyphs` directory. Patching CaskaydiaCove fails if only files specified in No.2 are present.
. The file name is `codicon.ttf` (no plural `s`) as of 06/01/2023. +
. -
. Change the command as pointed out in No.4. +
** `<your font>` is path to font file.
** `font-patcher` v3 requires `--makegroups 0` option.
** You might need to edit the first line of `font-pather` and change it to `python3`
** The argument to `--custom` is relative to `src/glyphs` directory.
. Double click the patched font and install it. +
** Restarting windows terminal is required to pick up the newly installed font.

Cursor::
[source,json]
----
"cursorShape": "filledBox"
"colorScheme": "Campbell"
----

Other setting::
[source,json]
----
"bellStyle": "none",
"tabSwitcherMode": "disabled",
"suppressApplicationTitle": true,
"scrollbarState": "hidden",
"trimBlockSelection": true
----

=== Ubuntu
Go to ubuntu section `profiles -> list`

==== Change starting directory
. Add `"startingDirectory": "//wsl$/Ubuntu/<linux path to directory>"` to the
   section. +
   eg. `"startingDirectory": "//wsl$/Ubuntu/home/user"`

=== Keybind
Replace original copy/paste keybind under `keybindings` with the below snippet.
[source,json]
----
        {
            "id": "Terminal.CopyToClipboard",
            "keys": "ctrl+shift+c"
        },
        {
            "id": "Terminal.PasteFromClipboard",
            "keys": "ctrl+shift+v"
        },
----

Add the below to the root. `actions` field defines the functions for keybinds.
[source,json]
----
    "actions": 
    [
        {
            "command": 
            {
                "action": "moveTab",
                "direction": "backward"
            },
            "id": "User.moveTab.backward"
        },
        {
            "command": 
            {
                "action": "moveTab",
                "direction": "forward"
            },
            "id": "User.moveTab.forward"
        },
        {
            "command": "openTabRenamer",
            "id": "User.openTabRenamer"
        }
    ],
----

Add the below to `keybindings`.
[source,json]
----
        {
            "id": null,
            "keys": "ctrl+comma"
        },
        {
            "id": null,
            "keys": "ctrl+shift+w"
        },
                {
            "id": "User.moveTab.backward",
            "keys": "ctrl+shift+h"
        },
        {
            "id": "User.openTabRenamer",
            "keys": "ctrl+shift+r"
        },
        {
            "id": "User.moveTab.forward",
            "keys": "ctrl+shift+l"
        },
        {
            "id": null,
            "keys": "win+sc(41)"
        }
----

=== Misc
Prevent cursor from blinking::
Put below in the rc file of your shell.
[source,sh]
----
printf '\033[?12l'
----
