# e.g. jupyter-lab [--ip <ip>] [--port <port>]
mod go

default:
	just --list --unsorted

jupyter *flags:
	jupyter-lab {{flags}}

jupytext-to-md file:
	jupytext --to markdown {{invocation_directory() / file}}

jupytext-to-ipynb file:
	jupytext --to ipynb {{invocation_directory() / file}}
