= blackbox exporter

== Debugging
ref: https://www.robustperception.io/debugging-blackbox-exporter-failures/

=== Manual query
Login to blackbox exporter server, and query localhost with `debug` parameter as in: +
`http://localhost:9115/probe?debug=true&module=http_2xx&taget=<URL of monitoring target>` +
If the value of `target` contains query parameter, all `&` must be URL encoded to `%26` or parameters after the first `&` will be removed. +
Also, all `%` must be encoded to `%25` so that the URL is not fully decoded before actually probing the monitoring target.

NOTE: Adding `debug: true` to `scrape_configs.params` adds the parameter to query from vmagent to blackbox exporter. +
But since vmagent expects the response from blackbox exporter as json but `debug` response includes non-json text, vmagent logs error messages and cannot see the debug contents.

[source,yaml]
----
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
      debug: true
  ...
----

=== Command line argument
The same info can be obtained by adding `--log.level=debug` flag.
