= WSL

== Install

=== Install without Microsoft Store
. For older builds of windows, run below commands on *Windows* PowerShell ass admin. +
+
[source,powershell]
----
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
----
. Download distributions
.. Go to https://docs.microsoft.com/en-us/windows/wsl/install-manual#downloading-distributions and copy the URL of distribution you want to install.
.. Run the command below (replace URL with the distribution of your choise). +
  `Invoke-WebRequest -Uri https://aka.ms/wslubuntu2004 -OutFile Ubuntu.appx -UseBasicParsing`
. Download and run the Linux kernel update package.
.. Download from https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
.. Run the downloaded file.
. Set WSL 2 as your default version.
  `wsl --set-default-version 2`
. Start WSL by opening Start menu and click the icon of the linux distribution.

== Basic
=== Shutdown the vm
`wsl.exe --shutdown`

== Setup
* Link to windows home directory +
  `ln -s /mnt/c/Users/<user>/ ~/winhome`
* Set `DISPLAY` environment varialbe to use `xclip`. +
** Install X server link:https://sourceforge.net/projects/vcxsrv/[VcXsrv]
** The value of `DISPLAY`
*** WSL1
**** `127.0.0.1:0.0`
*** WSL2
**** IP address of `nameserver` in `/etc/resolv.conf` with `:0.0` appended. +
**** e.g. `172.24.16.1:0.0`

== Configuration
=== Startup
You can configure things like mount path, network and inter-operability by +
editing (or create) `/etc/wsl.conf`. +
Refer to link:https://docs.microsoft.com/en-us/windows/wsl/wsl-config=set-wsl-launch-settings[this page] for more detail.

=== Spec
Memory, the number of processors, swap size and etc can be configured by editing
(or creating) `~/.wslconfig` on windows. +
Refer to link:https://www.bleepingcomputer.com/news/microsoft/windows-10-wsl2-now-allows-you-to-configure-global-options/[this page] for more detail.

== SSH
* IP address is either `127.0.0.1` or one under `eth0` of `ip addr` output.
* Change `PasswordAuthentication` to `yes` if you want to ssh with password.

== Misc
=== Connect to the Internet on VPN
Connecting to the Internet from WSL via VPN seems to fail, but link:https://github.com/sakai135/wsl-vpnkit[wsl-vpnkit] can solve that.

To install, run:
[source,shell]
----
wsl --import wsl-vpnkit $env:USERPROFILE\wsl-vpnkit wsl-vpnkit.tar.gz
----

To start wsl-vpnkit automatically, add the below to shell profile.
[source,fish]
----
wsl.exe -d wsl-vpnkit service wsl-vpnkit start 2> /dev/null
set -x DISPLAY host.internal:0.0
----
You might see an error saying `/mnt/c/WINDOWS/system32/wsl.exe` is not found. +
That is because `/mnt/c` is not mounted, and rebooting PC should solve.

[NOTE]
====
wsl-vpnkit has no effect inside docker container started in WSL.
You need Docker for Desktop. +
*2022/08/12:* Seems like it is possible to access the internet from inside
containers. Some say docker's network mode has to be `host`, but it worked
without `host`.
====

== Issues
* qutebrowser crashes
