= WSL

== Basic
=== Shutdown the vm
`wsl.exe --shutdown`

== Setup
* Link to windows home directory +
  `ln -s /mnt/c/Users/<user>/ ~/winhome`
* Set `DISPLAY` environment varialbe to use `xclip`. +
** Install X server link:https://sourceforge.net/projects/vcxsrv/[VcXsrv]
** The value of `DISPLAY` needs to be the IP address of `nameserver` in
  `/etc/resolv.conf` with `:0.0` appended. +
  e.g. `172.24.16.1:0.0`

== Configuration
=== Startup
You can configure things like mount path, network and inter-operability by +
editing (or create) `/etc/wsl.conf`. +
Refer to link:https://docs.microsoft.com/en-us/windows/wsl/wsl-config=set-wsl-launch-settings[this page] for more detail.

=== Spec
Memory, the number of processors, swap size and etc can be configured by editing
(or creating) `~/.wslconfig` on windows. +
Refer to link:https://www.bleepingcomputer.com/news/microsoft/windows-10-wsl2-now-allows-you-to-configure-global-options/[this page] for more detail.

== SSH
* IP address is either `127.0.0.1` or one under `eth0` of `ip addr` output.
* Change `PasswordAuthentication` to `yes` if you want to ssh with password.

== Misc
=== Connect to the Internet on VPN
Connecting to the Internet from WSL via VPN seems to fail, but link:https://github.com/sakai135/wsl-vpnkit[wsl-vpnkit] can solve that.

To install, run:
[source,shell]
----
wsl --import wsl-vpnkit $env:USERPROFILE\wsl-vpnkit wsl-vpnkit.tar.gz
----

To start wsl-vpnkit automatically, add the below to shell profile.
[source,fish]
----
wsl.exe -d wsl-vpnkit service wsl-vpnkit start 2> /dev/null
set -x DISPLAY host.internal:0.0
----
You might see an error saying `/mnt/c/WINDOWS/system32/wsl.exe` is not found. +
That is because `/mnt/c` is not mounted, and rebooting PC should solve.

NOTE: wsl-vpnkit has no effect inside docker container started in WSL.
You need Docker for Desktop.

== Issues
* qutebrowser crashes
